[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements-deploy.txt && pip uninstall -y opencv-python && pip install opencv-python-headless"
]

[start]
cmd = "uvicorn test.main:app --host 0.0.0.0 --port ${PORT}"
